apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: notes-app
spec:
  type: NodePort  # Change service type to NodePort
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007  # Specify a fixed NodePort (optional)
