apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: notes-app
spec:
  type: ClusterIP  # Ensure the service is of type ClusterIP
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8000
